### ISSUE TITLE
incomplete installation

### ISSUE THREAD

**Issue by ArnieBarney** [adnamsale/dropquotes#1]
I tried to install this program but after a success message by the installer I cannot find the program file or the ./build path indicated in the instructions to run the app. I'm running Win10 and jdk and jre 8

**Comment by adnamsale** [comment]
Well this is a bit of a stroll down memory lane. I certainly never tried this on Windows and it looks like I moved some things around after writing the readme. Anyhow, I was able to get it to run on Windows by following the build instructions as given and then running it with `cli\build\install\cli\bin\cli.bat`. It looks like dropquotes.com hasn't updated their web site in 6 years so the code to import the puzzle from the web page source still works.

**Comment by ArnieBarney** [comment]
Yes!! that worked for me too. Thank you so much for looking at it so quickly.
